package com.ejb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5.redhat-00001
 * 2020-04-10T13:54:59.012+05:30
 * Generated source version: 3.2.5.redhat-00001
 *
 */
@WebService(targetNamespace = "http://ejb.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ejb.com/", className = "com.ejb.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ejb.com/", className = "com.ejb.SayHelloResponse")
    public void sayHello();

    @WebMethod
    @RequestWrapper(localName = "sayName", targetNamespace = "http://ejb.com/", className = "com.ejb.SayName")
    @ResponseWrapper(localName = "sayNameResponse", targetNamespace = "http://ejb.com/", className = "com.ejb.SayNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
